language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
script:
  - pytest
  - autopep8 --diff --aggressive --aggressive --recursive --exit-code tic_tac_toe tests
  - pylint --rcfile=./pylintrc tic_tac_toe
